version: '3.7'

services:

  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - LOCAL_MODE=0
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  db:
