version: '3.7'

services:

  db:
    image: postgres:12.2-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  db:
