version: '3.7'

services:

  app:
    build:
      args:
        CURRENT_ENV: dev
    environment:
      - CURRENT_ENV=dev
    volumes:
      - .:/opt/app/
    command: ash -c "
      dockerize --wait-retry-interval 5s --timeout 100s -wait tcp://db:5432
      && alembic upgrade head
      && python3 main.py"
