version: '3.7'

services:

  app:
    image: serial-notifier-web:${PROD_IMAGE_TAG}
    environment:
      - CURRENT_ENV=prod
    command: bash -c "
      dockerize --wait-retry-interval 5s --timeout 100s -wait tcp://db:5432
      && alembic upgrade head
      && gunicorn -c gunicorn.conf.py 'main:app_factory'"

  web-server:
    restart: on-failure
    image: nginx:1.17.1-alpine
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./static/:/opt/app/static/
      - ./conf_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
