"""add_table_source_info

Revision ID: 63678899e054
Revises: b8c8e0c4f445
Create Date: 2020-04-05 20:12:15.662570

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '63678899e054'
down_revision = 'b8c8e0c4f445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'source_info',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('site_name', sa.Unicode(length=15), nullable=False),
        sa.Column('encoding', sa.Unicode(length=10), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('source', sa.Column('id_source_info', sa.Integer(), nullable=True))
    op.alter_column('source', 'url', existing_type=sa.VARCHAR(length=300), nullable=False)
    op.create_foreign_key(None, 'source', 'source_info', ['id_source_info'], ['id'])
    op.drop_column('source', 'site_name')
    op.drop_column('source', 'encoding')
    # ### end Alembic commands ###


def downgrade():
    op.add_column('source', sa.Column('encoding', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('source', sa.Column('site_name', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_constraint('source_id_source_info_fkey', 'source', type_='foreignkey')
    op.alter_column('source', 'url', existing_type=sa.VARCHAR(length=300), nullable=True)
    op.drop_column('source', 'id_source_info')
    op.drop_table('source_info')
