"""add_user_model

Revision ID: 6fc9fa4a6ba3
Revises: 
Create Date: 2020-03-19 17:52:56.906939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6fc9fa4a6ba3'
down_revision = None
branch_labels = None
depends_on = None

sex = ('male', 'female')
sex_enum = sa.Enum(*sex, name='sex')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sex', sex_enum, nullable=True),
        sa.Column('nick', sa.Unicode(length=50), nullable=False),
        sa.Column('name', sa.Unicode(length=50), nullable=True),
        sa.Column('surname', sa.Unicode(length=50), nullable=True),
        sa.Column('password', sa.Unicode(length=70), nullable=False),
        sa.Column('email', sa.Unicode(length=80), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('reg_date', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('nick'),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('user')
    sex_enum.drop(op.get_bind())
