"""add_telegram_acc

Revision ID: e947ed61465e
Revises: 8fa487579879
Create Date: 2020-11-23 22:57:49.527173

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e947ed61465e'
down_revision = '8fa487579879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'episode_number', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('episode', 'id_tv_show', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('episode', 'season_number', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('source', 'id_source_info', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('source', 'id_tv_show', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('tv_show', 'name', existing_type=sa.VARCHAR(length=150), nullable=False)
    op.alter_column('user_episode', 'id_episode', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('user_episode', 'id_user', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_episode', 'id_user', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('user_episode', 'id_episode', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('tv_show', 'name', existing_type=sa.VARCHAR(length=150), nullable=True)
    op.alter_column('source', 'id_tv_show', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('source', 'id_source_info', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('episode', 'season_number', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('episode', 'id_tv_show', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('episode', 'episode_number', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
