version: '3.7'

services:

  app:
    image: registry.gitlab.com/alex925/serial-notifier-web/app:develop
    restart: on-failure:10
    env_file:
      - .env
    environment:
      - LOCAL_MODE=0
    ports:
      - 127.0.0.1:8080:8080
    links:
      - db
    depends_on:
      - db

  scheduler:
    image: registry.gitlab.com/alex925/serial-notifier-web/app:develop
    restart: on-failure:10
    env_file:
      - .env
    environment:
      - LOCAL_MODE=0
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:12
    restart: on-failure:10
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
