version: '3.7'

services:

  app:
    image: registry.gitlab.com/alex925/serial-notifier-web/app:${PROD_IMAGE_TAG}
    environment:
      - CURRENT_ENV=prod
    command: bash -c "
      dockerize --wait-retry-interval 5s --timeout 100s -wait tcp://db:${POSTGRES_PORT}
      && alembic upgrade head
      && cd ./src
      && gunicorn -c ../conf_files/gunicorn/gunicorn_conf.py wsgi:app"

  scheduler:
    image: registry.gitlab.com/alex925/serial-notifier-web/app:${PROD_IMAGE_TAG}
    environment:
      - CURRENT_ENV=prod
    command: bash -c "
      dockerize --wait-retry-interval 5s --timeout 100s -wait tcp://db:${POSTGRES_PORT}
      && python ./src/scheduler.py"

  nginx:
    restart: on-failure:10
    image: nginx:1.17.1
    ports:
      - 8081:80
    links:
      - app
    volumes:
      - ./static/:/opt/app/static/
      - ./conf_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
